# -*- coding: utf-8 -*-
"""DATMIN_Modul 2_NOVI_RAYYANMUHAMMADHAFIDZ_1020424000137.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWIxA21MsGTS8yDL5gCWKGLbcGR2JYZX
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_csv( '/content/drive/MyDrive/Colab Notebooks/Diabetes_dataset_2026_ver3.csv', sep=';')
df.head()

df.info()

print(df['BMI'].value_counts())

df.describe()

print("jumlah data kosong =")
print(df.isnull().sum())
print(f'\njumlah data duplikat = {df.duplicated().sum()}')

print("\n Matriks Korelasi ")
correlation_matrix = df.corr()
print(correlation_matrix)

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='RdYlGn')
plt.title('Heatmap Korelasi Fitur')
plt.tight_layout()
plt.show()

sns.set_theme(style="whitegrid")
df.hist(bins=20, figsize=(20, 15), color='skyblue', edgecolor='black')
plt.suptitle('Distribusi Seluruh Fitur - Diabetes Dataset', fontsize=20)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

df.fillna(df.median(numeric_only=True), inplace=True)
print(df.describe())

def fix_health_data(row):
    # Koreksi bagi 10 (hasil 1 desimal)
    if row['HbA1c'] > 20:
        row['HbA1c'] = round(row['HbA1c'] / 10, 1)
    if row['Glucose'] > 300:
        row['Glucose'] = round(row['Glucose'] / 10, 1)
    if row['BloodPressure'] > 200:
        row['BloodPressure'] = round(row['BloodPressure'] / 10, 1)

    # Profil Lipid (LDL/HDL/Triglycerides)
    for col in ['LDL', 'HDL', 'Triglycerides']:
        if row[col] > 600:
            row[col] = round(row[col] / 10, 1)

    # Lingkar Pinggang/Pinggul (Waist/Hip)
    for col in ['WaistCircumference', 'HipCircumference']:
        if row[col] > 300:
            row[col] = round(row[col] / 10, 1)

    # Koreksi bagi 100 (hasil 2 desimal)
    if row['BMI'] > 100:
        row['BMI'] = round(row['BMI'] / 100, 2)
    if row['WHR'] > 2:
        row['WHR'] = round(row['WHR'] / 100, 2)

    return row

df_fixed = df.apply(fix_health_data, axis=1)
print(df_fixed.describe())

vital_cols = ['BMI', 'Glucose', 'BloodPressure', 'HbA1c']
df_fixed[vital_cols] = df_fixed[vital_cols].replace(0, np.nan)
for col in vital_cols:
    median_val = df_fixed[col].median()
    df_fixed[col] = df_fixed[col].fillna(median_val)
print("5 Baris Pertama Setelah Imputasi Nol:")
print(df_fixed.head())

health_cols = ['BMI', 'Glucose', 'BloodPressure', 'HbA1c', 'LDL', 'HDL', 'Triglycerides', 'WHR']
summary_stats = df_fixed[health_cols].describe().loc[['mean', 'min', 'max']]
print("\nRingkasan Statistik Deskriptif (Kesehatan Utama):")
print(summary_stats)

exclude_cols = ['FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse', 'Outcome']
numeric_cols = [col for col in df_fixed.columns if col not in exclude_cols]

def get_outlier_counts(data, cols):
    counts = {}
    for col in cols:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        counts[col] = ((data[col] < lower) | (data[col] > upper)).sum()
    return counts
outliers_before = get_outlier_counts(df_fixed, numeric_cols)
for col in numeric_cols:
    Q1 = df_fixed[col].quantile(0.25)
    Q3 = df_fixed[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_fixed[col] = np.where(df_fixed[col] < lower_bound, lower_bound,
                             np.where(df_fixed[col] > upper_bound, upper_bound, df_fixed[col]))

outliers_after = get_outlier_counts(df_fixed, numeric_cols)
verification = pd.DataFrame({
    'Outliers Sebelum': outliers_before,
    'Outliers Sesudah': outliers_after
})
print(verification)

bmi_frequency = df_fixed['BMI'].value_counts().sort_index()
print("Nilai BMI dengan frekuensi tertinggi:")
print(df_fixed['BMI'].value_counts().head(10))
print(f"\nNilai BMI Minimum (Batas Bawah): {df_fixed['BMI'].min()}")
print(f"Nilai BMI Maksimum (Batas Atas): {df_fixed['BMI'].max()}")
lower_bound_count = (df_fixed['BMI'] == df_fixed['BMI'].min()).sum()
print(f"\nJumlah data pada batas bawah (capping): {lower_bound_count}")

from sklearn.model_selection import train_test_split

X = df.drop(columns=['Glucose'])
y = df['Glucose']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Membuat scatter plot nilai aktual vs prediksi
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)

# Menambahkan garis diagonal y=x sebagai referensi
max_val = max(max(y_test), max(y_pred))
min_val = min(min(y_test), min(y_pred))
plt.plot([min_val, max_val], [min_val, max_val], color='red', lw=2, linestyle='--')

plt.xlabel('Nilai Aktual (Glucose)')
plt.ylabel('Nilai Prediksi (Glucose)')
plt.title('Perbandingan Nilai Aktual vs Nilai Prediksi')
plt.grid(True)
plt.show()

from sklearn.preprocessing import StandardScaler
exclude_cols = ['FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse', 'Outcome']
numeric_cols = [col for col in df.columns if col not in exclude_cols]
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
print(df.head())

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Calculate distortion/inertia for a range of k values
inertia = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(df)
    inertia.append(kmeans.inertia_)

# Plotting the Elbow Method visualization
plt.figure(figsize=(10, 6))
plt.plot(K_range, inertia, marker='o', linestyle='--', color='b')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia / Distortion')
plt.title('Elbow Method for Optimal k')
plt.xticks(K_range)
plt.grid(True)
plt.show()

print("Berdasarkan grafik Elbow Method di atas, titik di mana penurunan inertia mulai melambat (membentuk siku) menunjukkan nilai k optimal.")
print("Nilai k optimal yang diperoleh adalah: 3")

from sklearn.metrics import silhouette_score

silhouette_scores = []
K_range = range(2, 11) # Silhouette score requires at least 2 clusters

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(df)
    score = silhouette_score(df, labels)
    silhouette_scores.append(score)
    print(f"Silhouette Score untuk k={k}: {score:.4f}")

# Menentukan k terbaik
best_k = K_range[np.argmax(silhouette_scores)]
best_score = max(silhouette_scores)

print(f"\nJumlah cluster (k) terbaik berdasarkan Silhouette Score adalah k={best_k} dengan skor {best_score:.4f}")

# Melakukan clustering dengan k optimal (k=2)
kmeans_final = KMeans(n_clusters=2, random_state=42, n_init=10)
df['Cluster'] = kmeans_final.fit_predict(df)

print("Clustering selesai. Label cluster telah ditambahkan ke DataFrame.")
display(df[['Cluster']].head())

from sklearn.decomposition import PCA

# 1. Menyiapkan fitur (tanpa kolom Cluster)
X_features = df.drop(columns=['Cluster'])

# 2. Inisialisasi PCA untuk 2 dimensi
pca = PCA(n_components=2)
pca_result = pca.fit_transform(X_features)

# 3. Mentransformasikan Centroids ke dalam ruang PCA yang sama
# Mengonversi centroids ke DataFrame agar memiliki nama fitur yang sama dengan data fitting
centroids = pd.DataFrame(kmeans_final.cluster_centers_, columns=X_features.columns)
centroids_pca = pca.transform(centroids)

# 4. Membuat DataFrame untuk plotting
df_pca_viz = pd.DataFrame(data=pca_result, columns=['PC1', 'PC2'])
df_pca_viz['Cluster'] = df['Cluster'].values

# 5. Visualisasi
plt.figure(figsize=(12, 8))
sns.scatterplot(x='PC1', y='PC2', hue='Cluster', data=df_pca_viz, palette='viridis', alpha=0.5, s=50)

# Plot Centroids
plt.scatter(centroids_pca[:, 0], centroids_pca[:, 1], c='red', s=250, marker='X', label='Centroids', edgecolor='black')

plt.title('Visualisasi Cluster & Centroids Diabetes (PCA 2D)', fontsize=15)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

print(f"Rasio varians yang dijelaskan: {pca.explained_variance_ratio_.sum():.2%}")

"""### Persiapan Data untuk Klasifikasi
Langkah-langkah berikut mencakup pembagian data dan standarisasi fitur.
"""

# 1. Impor fungsi yang diperlukan
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df_fixed.drop(columns=['Outcome'])
y = df_fixed['Outcome']

x_nb_train, x_nb_test, y_nb_train, y_nb_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler_nb = StandardScaler()
x_nb_train = scaler_nb.fit_transform(x_nb_train)
x_nb_test = scaler_nb.transform(x_nb_test)

x_nb_full_scaled = scaler_nb.fit_transform(X)

print("Pembagian data dan standarisasi selesai.")

from sklearn.naive_bayes import GaussianNB
naive_bayes = GaussianNB()
naive_bayes.fit(x_nb_train, y_nb_train)
y_pred_nb = naive_bayes.predict(x_nb_test_)

"""### 6. Evaluasi Model Naive Bayes"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Evaluate the model using Naive Bayes test target and predictions
accuracy_nb = accuracy_score(y_nb_test, y_pred_nb)
precision_nb = precision_score(y_nb_test, y_pred_nb, average='weighted', zero_division=0)
recall_nb = recall_score(y_nb_test, y_pred_nb, average='weighted', zero_division=0)
f1_nb = f1_score(y_nb_test, y_pred_nb, average='weighted', zero_division=0)
conf_matrix_nb = confusion_matrix(y_nb_test, y_pred_nb)
class_report_nb = classification_report(y_nb_test, y_pred_nb, zero_division=0)

print(f"Naive Bayes Model Evaluation:\n")
print(f"Accuracy: {accuracy_nb:.4f}")
print(f"Precision: {precision_nb:.4f}")
print(f"Recall: {recall_nb:.4f}")
print(f"F1-Score: {f1_nb:.4f}")
print(f"\nConfusion Matrix:\n{conf_matrix_nb}")
print(f"\nClassification Report:\n{class_report_nb}")

from imblearn.over_sampling import SMOTE
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix




# Display class distribution before sampling
print("Class distribution in training data before sampling:")
print(pd.Series(y_nb_train).value_counts())

smote = SMOTE(random_state=42)
x_nb_train_resampled, y_nb_train_resampled = smote.fit_resample(x_nb_train, y_nb_train)
print(f"\nClass distribution in training data after SMOTE sampling:")
print(pd.Series(y_nb_train_resampled).value_counts())

naive_bayes_model_smote = GaussianNB()
naive_bayes_model_smote.fit(x_nb_train_resampled, y_nb_train_resampled)
y_pred_nb_smote = naive_bayes_model_smote.predict(x_nb_test)

print(f"\n--- Naive Bayes Model Evaluation (SMOTE) ---\n")
print(classification_report(y_nb_test, y_pred_nb_smote))

fig, ax = plt.subplots(1, 2, figsize=(8, 6))
cm_original = confusion_matrix(y_nb_test, y_pred_nb)
sns.heatmap(cm_original, annot=True, fmt='d', cmap='Blues', ax=ax[0])
ax[0].set_title('Confusion Matrix (Original)')
ax[0].set_xlabel('Predicted')
ax[0].set_ylabel('Actual')
print("\n")

cm_resampled = confusion_matrix(y_nb_test, y_pred_nb_smote)
sns.heatmap(cm_resampled, annot=True, fmt='d', cmap='Blues', ax=ax[1])
ax[1].set_title('Confusion Matrix (SMOTE)')
ax[1].set_xlabel('Predicted')
ax[1].set_ylabel('Actual')

"""### 8. Export Model dan Scaler ke File .pkl"""

import pickle
import os

# 1. Simpan model Linear Regression dan Scaler-nya
with open('linear_regression_model.pkl', 'wb') as f:
    pickle.dump(model, f)
with open( 'linear_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

# 2. Simpan model Naive Bayes (SMOTE) dan Scaler-nya
with open('naive_bayes_smote_model.pkl', 'wb') as f:
    pickle.dump(naive_bayes_model_smote, f)
with open('naive_bayes_scaler.pkl', 'wb') as f:
    pickle.dump(scaler_nb, f)

print("Konfirmasi: Seluruh model dan scaler telah berhasil disimpan di folder:")

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip install -q streamlit


import streamlit as st
import pickle
import numpy as np
import pandas as pd

# Writing the Streamlit app to a file correctly using triple quotes
with open('app.py', 'w') as f:
    f.write('''
import streamlit as st
import pickle
import numpy as np
import pandas as pd

# Load models and scalers
with open('linear_regression_model.pkl', 'rb') as f:
    lr_model = pickle.load(f)
with open('linear_scaler.pkl', 'rb') as f:
    lr_scaler = pickle.load(f)
with open('naive_bayes_smote_model.pkl', 'rb') as f:
    nb_model = pickle.load(f)
with open('naive_bayes_scaler.pkl', 'rb') as f:
    nb_scaler = pickle.load(f)

# Sidebar Navigation
st.sidebar.title("Dashboard Diabetes")
page = st.sidebar.radio("Pilih Halaman:", ["Prediksi Glucose (Linear Regression)", "Klasifikasi Outcome (Naive Bayes)"])

if page == "Prediksi Glucose (Linear Regression)":
    st.title("📈 Prediksi Kadar Glucose")
    st.write("Masukkan data fitur untuk memprediksi nilai Glucose.")

    lr_features = ['Age', 'Pregnancies', 'BMI', 'BloodPressure', 'HbA1c', 'LDL', 'HDL', 'Triglycerides', 'WaistCircumference', 'HipCircumference', 'WHR', 'FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse', 'Outcome']

    input_data = []
    col1, col2 = st.columns(2)
    for i, feat in enumerate(lr_features):
        with col1 if i % 2 == 0 else col2:
            val = st.number_input(f"{feat}", value=0.0, key=f"lr_{feat}")
            input_data.append(val)

    if st.button("Hitung Prediksi Glucose"):
        input_arr = np.array([input_data])
        scaled_data = lr_scaler.transform(input_arr)
        prediction = lr_model.predict(scaled_data)
        st.success(f"Prediksi Nilai Glucose: {prediction[0]:.2f}")

elif page == "Klasifikasi Outcome (Naive Bayes)":
    st.title("🩺 Klasifikasi Risiko Diabetes")
    st.write("Masukkan data fitur untuk menentukan klasifikasi Outcome (Diabetes/Tidak).")

    nb_features = ['Age', 'Pregnancies', 'BMI', 'Glucose', 'BloodPressure', 'HbA1c', 'LDL', 'HDL', 'Triglycerides', 'WaistCircumference', 'HipCircumference', 'WHR', 'FamilyHistory', 'DietType', 'Hypertension', 'MedicationUse']

    input_data = []
    col1, col2 = st.columns(2)
    for i, feat in enumerate(nb_features):
        with col1 if i % 2 == 0 else col2:
            val = st.number_input(f"{feat}", value=0.0, key=f"nb_{feat}")
            input_data.append(val)

    if st.button("Klasifikasi Data"):
        input_arr = np.array([input_data])
        scaled_data = nb_scaler.transform(input_arr)
        prediction = nb_model.predict(scaled_data)

        if prediction[0] == 1:
            st.error("Hasil: Diabetes (Positif)")
        else:
            st.success("Hasil: Tidak Diabetes (Negatif)")
''')

print("File app.py berhasil dibuat.")

!pip install pyngrok
from pyngrok import ngrok
import subprocess
import time

# Masukkan Auth Token Ngrok
ngrok.set_auth_token("3DFZMTfRieYmQpmrNh7dsOW9W25_6MvX5Mjdp7GWNZqZFaUnL")
ngrok.kill()

# Menjalankan Streamlit di background
process = subprocess.Popen(
    ["streamlit", "run", "app.py",
     "--server.port=8501",
     "--server.headless=true",
     "--server.enableCORS=false",
     "--server.enableXsrfProtection=false"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Tunggu beberapa detik agar server siap
time.sleep(5)

# Membuat tunnel publik
public_url = ngrok.connect(8501)
print(f"✅ Dashboard live di: {public_url}")

"""### 4. Penjelasan Export Model dan Scaler

**Mengapa model perlu di-export menggunakan Pickle?**
Model perlu di-export agar hasil pelatihan yang memakan waktu dan sumber daya tidak hilang saat runtime berakhir. Dengan menyimpannya ke format `.pkl`, kita dapat memuat kembali model tersebut di lingkungan produksi atau aplikasi lain tanpa harus melatih ulang datanya dari awal.

**Apa kegunaan menyimpan scaler secara terpisah?**
Scaler harus disimpan karena data baru yang akan diprediksi di masa depan harus melalui **transformasi yang persis sama** (mean dan standar deviasi yang sama) dengan data yang digunakan saat pelatihan. Jika kita menggunakan scaler baru atau tidak melakukan standarisasi pada data input baru, model akan menerima data dengan distribusi yang berbeda, yang mengakibatkan prediksi menjadi tidak akurat atau salah.

### Confusion Matrix dan Classification Report

### 5. Mengapa proses standarisasi perlu dilakukan?

Proses standarisasi perlu dilakukan sebelum membangun model klasifikasi karena:

1.  **Skala yang Berbeda:** Fitur dalam dataset (seperti Age vs Glucose) memiliki rentang nilai yang sangat berbeda. Tanpa standarisasi, fitur dengan nilai besar akan mendominasi perhitungan model.
2.  **Algoritma Berbasis Jarak:** Banyak algoritma klasifikasi (seperti KNN atau SVM) sangat sensitif terhadap skala karena mereka menghitung jarak antar titik data.
3.  **Konvergensi Gradien:** Untuk algoritma yang menggunakan optimasi gradien (seperti Logistic Regression atau Neural Networks), standarisasi membantu model mencapai titik optimal (konvergensi) dengan lebih cepat dan stabil.
"""